### ISSUE TITLE
Errors while running test.py

### ISSUE THREAD

**Issue by zhenyinzhang** [nnaisense/bayesian-flow-networks#5]
When I try to run
```bash
python test.py seed=1 config_file=./configs/mnist_discrete.yaml load_model=./pretrained-BFNs/mnist_ema.pt n_steps=784 n_repeats=2000
```
to test the pre-trained model, I got this error info says
`ImportError: cannot import name 'get_generator' from 'utils_train'`
(I've already run `git clone git@hf.co:rupspace/pretrained-BFNs` successfully.)

I checked utils_train.py and found that there is no `get_generator`. However, I see function `get_generator` in its history commit 834d896:
```python
def get_generator(seed: int):
    g = torch.Generator()
    g.manual_seed(seed)
    return g
```

After adding this function to `utils_train.py`, the error info changed to:
```
UnpicklingError: Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if 
you get the file from a trusted source. WeightsUnpickler error: Unsupported operand 118
```

I tried to change `weights_only` from True to False, but it doesn't work.

Then I changed the model to my own checkpoint at `./checkpoints/BFN/best/ema_model.pt` (trained with your code, of course), with `weights_only` as True, problem solved.

Therefore, there might be some code to fix and models to update. :-)

**Comment by flukeskywalker** [comment]
Thanks for the report. I'll look into this soon.

**Comment by flukeskywalker** [comment]
Hi. I've removed the use of `get_generator()` from the code, as previously done for the training script.

The checkpoints appeared to have no issue on macos, but failed on linux. I saved them again and tested that loading is working on linux now. I'm updating the files on HF.

Thanks again for the report, and please re-open the issue if the fixes don't work for you!
