### ISSUE TITLE
 pre-trained model 

### ISSUE THREAD

**Issue by shen123ji** [nnaisense/bayesian-flow-networks#8]
Is there a pre-trained model here?

**Comment by shen123ji** [comment]
Can i have your text8_ema.pt and cifar10_256c_ema.pt？

**Comment by flukeskywalker** [comment]
Pretrained models are hosted on huggingface. You can do `git clone git@hf.co:rupspace/pretrained-BFNs`. Make sure you have git-lfs installed.

**Comment by shen123ji** [comment]
Thanks，i got it！



---Original---
From: "Rupesh K ***@***.***&gt;
Date: Wed, Jul 17, 2024 14:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [nnaisense/bayesian-flow-networks]  pre-trained model  (Issue #8)




 
Pretrained models are hosted on huggingface. You can do git clone ***@***.***:rupspace/pretrained-BFNs. Make sure you have git-lfs installed.
